# Generated by Django 5.1.1 on 2024-09-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_isOccupied', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tenant_firstName', models.CharField(max_length=32)),
                ('Tenant_lastName', models.CharField(max_length=32)),
                ('Tenant_email', models.EmailField(max_length=64, unique=True)),
                ('Tenant_password', models.CharField(max_length=64)),
            ],
        ),
    ]
