# Generated by Django 5.1.1 on 2024-09-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='Room_image',
            field=models.ImageField(default='assets/test1.png', upload_to='assets'),
        ),
    ]
