# Generated by Django 5.1.1 on 2024-09-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movein', '0002_room_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Announce_header', models.TextField()),
                ('Announce_body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Property_name', models.TextField()),
                ('Property_roomNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reports_header', models.TextField()),
                ('Reports_body', models.TextField()),
                ('Reports_author', models.CharField(max_length=128)),
                ('Reports_isCompleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='Tenant_email',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='Tenant_password',
        ),
        migrations.AddField(
            model_name='room',
            name='Room_tenant',
            field=models.CharField(default='Tenant', max_length=128),
        ),
    ]
