# Generated by Django 5.1.1 on 2024-09-26 16:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movein', '0003_announcements_property_reports_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcements',
            name='Announce_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='announcements',
            name='Announce_image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AlterField(
            model_name='announcements',
            name='Announce_header',
            field=models.CharField(max_length=100),
        ),
    ]
