# Generated by Django 5.1.1 on 2024-09-27 06:07

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movein', '0004_announcements_announce_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='Tenant_Email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='Tenant_Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
